### ISSUE TITLE
Does ridables modify the spawning conditions of vanilla mobs?

### ISSUE THREAD

**Issue by mibby** [BillyGalbreath/Ridables#36]
I noticed a few settings that touched up on whether mobs can spawn or not naturally. Does Ridables modify / overwrite the vanilla spawning conditions at all or is it applied additionally?

Edit: I am getting reports that blaze do a ton extra damage compared to before, so at the very least the AI settings overwrite vanilla.

```
ai:
  melee-damage: 6.0
  follow-range: 48.0
  shoot:
    speed: 1.0
    impact-damage: 6.0
    explosion-damage: 17.0
    explosion-fire: true
    grief: true
```
