### ISSUE TITLE
NoCheatPlus compatibility.

### ISSUE THREAD

**Issue by mibby** [BillyGalbreath/Ridables#39]
Would it be possible to add a hook compatibility for NoCheatPlus?

The cheat violation ``vehicle.vehicleenvelope`` seems to occur and randomly teleport players to a different location when they try to ride a mob. Disabling that violation check in NCP, players can ride again.

```
    vehicle:
      preventdestroyown: true
      enforcelocation: default
      schedulesetbacks: default
      morepackets:
        active: false
        actions: cancel vl>20 log:morepackets:0:11:i cancel
      envelope:
        active: default
        actions: cancel vl>100 cancel log:vehicleenvelope:0:11:i
```
